name: Azure - Deploy
description: Builds the app in Azure for deployment and hosting


# Note: Azure says "always free for 750 hours" but they don't clarify that
# those hours are *total*, not per month or similar, so they never refill.
# See: https://dev.to/azure/azure-free-account-is-it-really-free-53cb


env:
  # See: https://github.com/Azure/webapps-deploy#configure-deployment-credentials
  WEBSITE_WEBDEPLOY_USE_SCM: true


inputs:
  GITHUB_TOKEN:
    description: GitHub token required for acting on repo within pipelines (modifying branches, publishing artifacts, etc.).
    required: true
  registryUrl:
    description: Docker image registry full URL.
    required: true


runs:
  using: composite
  steps:
    - name: Checkout repository branch
      uses: actions/checkout@v3

    - name: Azure - Cache name init
      uses: ./.github/workflows/actions/cache-name

    - name: Azure - Setup env
      id: azure-setup-env
      shell: bash
      run: |
        echo "GITHUB_TOKEN=${{ inputs.GITHUB_TOKEN }}" >> $GITHUB_ENV
        echo "registryUrl=${{ inputs.registryUrl }}" >> $GITHUB_ENV

    - name: Azure - Login
      id: azure-login
      uses: azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}

    - name: Azure - Deploy
      id: azure-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.REPO_NAME }}
        images: '${{ env.registryUrl }}:latest'
