# Render.com configuration
#
# See:
#   - https://render.com/docs/blueprint-spec
services:
  # A Docker web service
  - type: web
    name: anime-atsume
    env: docker
    repo: https://github.com/D-Pow/anime-atsume.git
    region: ohio
    plan: standard
    branch: master
    # rootDir: /home
    numInstances: 3 # optional (defaults to 1)
    # Overrides Dockerfile command
    # Expose both HTTP (80) and HTTPS (443) ports since render.com won't do it automatically for some reason
    # dockerCommand: docker run -it -p 80:8080 -p 443:8080 anime-atsume
    # Hacky workaround to run docker image without being forced to build it within Render.com
    # startCommand: node -e "require('child_process').spawnSync('bash', [ '-c', 'docker run -it -p 80:8080 -p 443:8080 anime-atsume' ], { env: process.env, stdio: [ process.stdin, process.stdout, process.stderr ], uiencoding: 'utf-8' })"
    # healthCheckPath: /
    envVars:
      - key: PORT
        value: 443
      # - key: JAVA_OPTS
      #   value: -Xmx640m
      # - key: REDIS_PORT
      #   fromService:
      #     type: redis
      #     name: lightning
      #     property: port
      # - fromGroup: my-settings
