name: Server - Verify and Build
description: Installs, tests, and builds the back-end


# This is for a sample Python back-end but it could easily be modified for any back-end system

runs:
  using: composite

  steps:
    - name: Checkout repository branch
      uses: actions/checkout@v3

    - name: Server Install
      id: server-install
      shell: bash
      working-directory: ./server/
      run: |
        echo "TODO"
