name: Server - Verify and Build
description: Installs, tests, and builds the back-end


# This is for a sample Python back-end but it could easily be modified for any back-end system

runs:
  using: composite
  steps:
    - name: Checkout repository branch
      uses: actions/checkout@v3

    - name: Server Build
      id: server-build
      shell: bash
      needs: [ client-build ]
      run: |
        cd ./server
        ./gradlew clean build

    - name: Server build output cache
      uses: actions/upload-artifact@v3
      needs: [ server-build ]
      with:
        name: ci-server-build-output
        path: |
          ./server/build/libs
